# Generated by Django 3.1.1 on 2020-09-04 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
                ('founder', models.CharField(max_length=60, verbose_name='Founder')),
                ('country', models.CharField(max_length=60, verbose_name='Country')),
            ],
        ),
        migrations.CreateModel(
            name='Tablet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
                ('storage_size', models.FloatField(blank=True, null=True, verbose_name='Storage size')),
                ('release_year', models.IntegerField(blank=True, null=True, verbose_name='Release')),
                ('brand', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='b_tablet', to='tablets.brand', verbose_name='Brand')),
            ],
        ),
    ]
