# Generated by Django 3.1.1 on 2020-09-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'brands'},
        ),
        migrations.AlterModelOptions(
            name='tablet',
            options={'verbose_name': 'tablets'},
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name='Name'),
        ),
    ]
