# Generated by Django 3.1.1 on 2020-09-04 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablets', '0002_auto_20200904_1708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tablet',
            options={},
        ),
    ]
