# Generated by Django 3.1.1 on 2020-09-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablets', '0003_auto_20200904_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablet',
            name='picture',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='release_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Release year'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='storage_size',
            field=models.FloatField(blank=True, null=True, verbose_name='Storage size en megabyte (MB)'),
        ),
    ]
