# Generated by Django 3.1.1 on 2020-09-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablets', '0004_auto_20200905_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablet',
            name='picture',
            field=models.ImageField(blank=True, upload_to='pictures'),
        ),
    ]
