# Generated by Django 3.1.1 on 2020-09-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablets', '0005_auto_20200905_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablet',
            name='picture',
            field=models.ImageField(blank=True, upload_to='static/pictues'),
        ),
    ]
