# Generated by Django 3.1.1 on 2020-09-05 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablets', '0007_auto_20200905_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablet',
            name='picture',
            field=models.ImageField(upload_to='tablets/static/pictures'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='release_year',
            field=models.IntegerField(null=True, verbose_name='Release year'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='storage_size',
            field=models.FloatField(null=True, verbose_name='Storage size en gega bytes (GB)'),
        ),
    ]
