# Generated by Django 3.1.1 on 2020-09-06 23:47

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tablets', '0008_auto_20200905_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='storage_size',
            field=models.FloatField(null=True, verbose_name='Storage size en Gigabytes (Gb)'),
        ),
    ]
