# Generated by Django 3.1.1 on 2020-09-07 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablets', '0010_auto_20200907_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name='Name of the Brand'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name='Name of Tablet'),
        ),
    ]
