# Generated by Django 3.1.1 on 2020-09-07 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablets', '0011_auto_20200907_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.ImageField(default='logo', upload_to='tablets/static/pictures'),
        ),
        migrations.AddField(
            model_name='tablet',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description of the Tablet'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name='Name of the Tablet'),
        ),
    ]
